FROM rust:1.84 as builder
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
ENV SQLX_OFFLINE=true
WORKDIR /app
COPY core_engine ./core_engine
WORKDIR /app/core_engine
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/core_engine/target/release/core_engine ./core_engine
CMD ["./core_engine"]
