FROM rust:1.78 as builder
WORKDIR /app
COPY core_engine ./core_engine
WORKDIR /app/core_engine
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/core_engine/target/release/core_engine ./core_engine
CMD ["./core_engine"]
